name: Lint and test

on: [push]

jobs:
  LintAndTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm i
    - name: Lint
      run: npm run lint
    - name: Compile
      run: npm run build
    - name: Test
      run: npm run test
      env:
        CI: true